export const movies =[
  {
    movie_aid:1,
    movie_title:"Spy Family Code: White",
    movie_year:"2023",
    movie_duration:"1hr 50min", 
    movie_category:"Anime", 
    movie_genre:"Comedy", 
    movie_summary:"After receiving an order to be replaced in Operation Strix, Loid decides to help Anya win a cooking competition at Eden Academy, by making the director's favorite meal in order to prevent his replacement.", 
    movie_cast:"Takuya Eguchi, Atsumi Tanezaki, Saori Hayami", 
    movie_image:"series-5.png", 
    movie_rating:"R-16",
    movie_is_active:true,
  },
  {
    movie_aid:2,
    movie_title:"Young Sheldon",
    movie_year:"2017",
    movie_duration:"7 Seasons", 
    movie_category:"International", 
    movie_genre:"Sitcom", 
    movie_summary:"Meet a child genius named Sheldon Cooper (already seen as an adult in The Big Bang Theory (2007)) and his family. Some unique challenges face Sheldon, who is socially impaired.", 
    movie_cast:"Iain Armitage, Zoe Perry, Lance Barber", 
    movie_image:"series-1.jpg", 
    movie_rating:"R-16",
    movie_is_active:true,
  },
  {
    movie_aid:3,
    movie_title:"Euphoria",
    movie_year:"2019",
    movie_duration:"2 Seasons ", 
    movie_category:"International", 
    movie_genre:"Drama", 
    movie_summary:"Rue Bennett is a drug addict fresh from rehab, who's struggling to stay clean and make sense of her future. Her life changes drastically when she meets Jules Vaughn, a trans girl who recently moved to town following her parents' divorce.", 
    movie_cast:"Zendaya, Hunter Schafer, Jacob Elordi", 
    movie_image:"series-2.jpg", 
    movie_rating:"R-18",
    movie_is_active:true,
  },
  {
    movie_aid:4,
    movie_title:"Queen Charlotte",
    movie_year:"2023",
    movie_duration:"1 Season", 
    movie_category:"International", 
    movie_genre:"History Drama", 
    movie_summary:"Betrothed against her will to King George, young Charlotte arrives in London on her wedding day and faces scrutiny from the monarch's cunning mother", 
    movie_cast:"India Amarteifio, Adjoa Andoh, Michelle Fairley", 
    movie_image:"series-3.jpg", 
    movie_rating:"R-18",
    movie_is_active:true,
  },
  {
    movie_aid:5,
    movie_title:"Going Seventeen: Don't Lie",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-1.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:6,
    movie_title:"Going Seventeen: Bad Clue",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-2.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:7,
    movie_title:"Going Seventeen: Mouse Buster",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-3.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:8,
    movie_title:"Going Seventeen: Multiverse",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-4.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:9,
    movie_title:"Going Seventeen: Ego",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-5.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:9,
    movie_title:"Going Seventeen: Seventeen",
    movie_year:"2023",
    movie_duration:"1hr 15mins", 
    movie_category:"Kdrama", 
    movie_genre:"TV Show", 
    movie_summary:"잘 지냈어요 모두 보고 싶었어 우리도 어쩜 이렇게 시간이 안 간는지 정말 버스 안에서 going 이불 속에서 going 고잉은 언제나 너에게 going going", 
    movie_image:"kdrama-6.jpg", 
    movie_rating:"R-17",
    movie_is_active:true,
  },
  {
    movie_aid:10,
    movie_title:"My Hero Academia: World Heroes' Mission",
    movie_year:"2021",
    movie_duration:"1hr 41mins", 
    movie_category:"Anime", 
    movie_genre:"TV Show", 
    movie_summary:"When a cult of terrorists ruins a city by releasing a toxin that causes people's abilities to spiral out of control, Japan's greatest heroes spread around the world in an attempt to track down the mastermind and put him to justice.", 
    movie_image:"youre next.jpg", 
    movie_rating:"R-15",
    movie_is_active:true,
  },
  {
    movie_aid:11,
    movie_title:"Ponyo",
    movie_year:"2008",
    movie_duration:"1hr 41mins", 
    movie_category:"Anime", 
    movie_genre:"Quest", 
    movie_summary:"A five-year-old boy develops a relationship with Ponyo, a young goldfish princess who longs to become a human after falling in love with him.", 
    movie_image:"ponyo.jpg", 
    movie_rating:"R-15",
    movie_is_active:true,
  },
  {
    movie_aid:12,
    movie_title:"Stand By Me",
    movie_year:"2014",
    movie_duration:"1hr 35mins", 
    movie_category:"Anime", 
    movie_genre:"Quest", 
    movie_summary:"What will happen to Nobita's life after Doraemon leaves?.", 
    movie_image:"standbyme.jpg", 
    movie_rating:"R-15",
    movie_is_active:true,
  },
  
]